// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA3Kdn9jOskcYEv8z42r5N-rlJS6lAQHY',
    appId: '1:432471515741:web:a7129d8b91bc1ed26023b4',
    messagingSenderId: '432471515741',
    projectId: 'my-islamy-app',
    authDomain: 'my-islamy-app.firebaseapp.com',
    storageBucket: 'my-islamy-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1wqYVbkv8KUuLmNBA-MXTLLA1vLb-usQ',
    appId: '1:432471515741:android:50f85345eee7997e6023b4',
    messagingSenderId: '432471515741',
    projectId: 'my-islamy-app',
    storageBucket: 'my-islamy-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiqmgSAVTqo7aLJ8d2-UGiyFJCc3OLYKU',
    appId: '1:432471515741:ios:5e1493896804f3326023b4',
    messagingSenderId: '432471515741',
    projectId: 'my-islamy-app',
    storageBucket: 'my-islamy-app.appspot.com',
    iosClientId: '432471515741-h98je963101fkghphcucn0d6ltvrkeuj.apps.googleusercontent.com',
    iosBundleId: 'com.example.myislamyap',
  );
}
